<?php
require __DIR__ . '/includes/config.php';
require __DIR__ . '/php/conexao.php';
require __DIR__ . '/includes/auth.php';
$email = 'ban_test_temp@techflow.local';
$db = db_connect();
$cleanup = $db->prepare('DELETE FROM usuarios WHERE email = ?');
$cleanup->bind_param('s', $email);
$cleanup->execute();
$hash = password_hash('Teste123', PASSWORD_DEFAULT);
$nome = 'Usuario Temporario';
$nasc = '1990-01-01';
$tipo = 'cliente';
$status = 'ativo';
$insert = $db->prepare("INSERT INTO usuarios (nome,email,nascimento,senha,tipo,is_admin,status_conta) VALUES (?,?,?,?,?,0,?)");
$insert->bind_param('ssssss', $nome, $email, $nasc, $hash, $tipo, $status);
$insert->execute();
$userId = $insert->insert_id;
$result = moderacao_atualizar_conta($userId, 'bloqueado');
$check = $db->prepare('SELECT status_conta FROM usuarios WHERE id = ?');
$check->bind_param('i', $userId);
$check->execute();
$row = $check->get_result()->fetch_assoc();
[$loginOk, $loginMessage] = login_user($email, 'Teste123');
echo json_encode(['function' => $result, 'saved_status' => $row['status_conta'] ?? null, 'login_ok' => $loginOk, 'login_message' => $loginMessage]);
$cleanup->execute();
